### ISSUE TITLE
Uncaught Error: Command failed: git branchfatal: not a git repository (or any of the parent dire...

### ISSUE THREAD

**Issue by threepistons** [AstrickHarren/git-merge#4]
To reproduce:
1. Commit to branch master
2. Checkout branch production
3. Click merge, red error message results with a button to submit this error report.

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Ubuntu 18.04.2
**Thrown From**: [git-merge](https://github.com/AstrickHarren/git-merge) package 0.2.0

### Stack Trace

Uncaught Error: Command failed: git branch
fatal: not a git repository (or any of the parent directories): .git

```
At child_process.js:655

Error: Command failed: git branch
fatal: not a git repository (or any of the parent directories): .git

    at checkExecSyncError (child_process.js:615:11)
    at Object.execSync (child_process.js:652:13)
    at Object.execSync (ELECTRON_ASAR.js:746:23)
    at Object.getBranch (/packages/git-merge/lib/git-command-util.js:9:25)
    at GitMergeView.updateSelection (/packages/git-merge/lib/git-merge-view.js:48:26)
    at /packages/git-merge/lib/git-merge-view.js:44:56)
```

### Commands

```
     -6:09.1.0 application:add-project-folder (input.hidden-input)
     -5:09.7.0 tree-view:duplicate (span.name.icon.icon-file-text)
     -5:05.9.0 core:move-right (input.hidden-input)
     -5:05.2.0 core:backspace (input.hidden-input)
     -5:03.8.0 core:confirm (input.hidden-input)
  2x -4:52.9.0 core:delete (input.hidden-input)
     -4:15 grammar-selector:show (atom-text-editor.editor.enable-atom-ide-find-references)
     -3:45.9.0 core:delete (input.hidden-input)
     -3:38.4.0 core:backspace (input.hidden-input)
     -3:03.0 intentions:highlight (input.hidden-input)
     -3:02.7.0 core:paste (input.hidden-input)
  5x -2:47.4.0 core:backspace (input.hidden-input)
     -2:43.5.0 intentions:highlight (input.hidden-input)
  5x -2:43.2.0 core:save (input.hidden-input)
 34x -2:28.4.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
aligner-puppet 0.1.1 
atom-ide-ui 0.13.0 
atom-svn-commit 0.1.1 
better-git-blame 0.4.7 
blame 1.1.0 
block-and-line-comment 0.4.0 
busy-signal 2.0.1 
comment 0.6.1 
git-merge 0.2.0 
hiera-eyaml 0.6.1 
ide-yaml 0.5.1 
intentions 1.1.5 
language-puppet 0.23.0 
linter 2.3.1 
linter-puppet-lint 0.8.4 
linter-ui-default 1.8.0 
markdown-toc 0.4.2 
minsky-link 0.0.16 
ruby-syntax-replacer 0.5.1 
svn 0.0.14 
workspace-stash 1.0.0 
```

**Comment by AstrickHarren** [comment]
@threepistons cannot reproduce the error though, trying. Anyway I think it probably has something to do with the way git-merge used to find path. I didn't know why the version on apm is still 0.2 though, trying to solve that first.
