### ISSUE TITLE
Uncaught TypeError: Cannot read property 'destroy' of null

### ISSUE THREAD

**Issue by taoualiw** [AstrickHarren/git-merge#5]
[Enter steps to reproduce:]

1. tried to merge a local branch into another

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.5
**Thrown From**: [git-merge](https://github.com/AstrickHarren/git-merge) package 0.4.1

### Stack Trace

Uncaught TypeError: Cannot read property 'destroy' of null

```
At /Users/wtaouali/.atom/packages/git-merge/lib/git-merge.js:41

TypeError: Cannot read property 'destroy' of null
    at /packages/git-merge/lib/git-merge.js:41:17
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1210649)
    at Project.addPath (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:410772)
    at confirm.n (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:715521)
    at CallbacksRegistry.apply (/Applications/Atom.app/Contents/Resources/electron.asar/common/api/callbacks-registry.js:47:25)
    at EventEmitter.ipcRenderer.on (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:285:21)
    at EventEmitter.emit (events.js:182:13)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-python 1.14.1 
busy-signal 2.0.1 
compare-files 0.8.1 
django-templates 0.5.0 
docblock-python 0.15.0 
file-icons 2.1.33 
git-merge 0.4.1 
git-time-machine 2.1.0 
highlight-selected 0.16.0 
intentions 1.1.5 
language-restructuredtext 1.1.2 
linter 2.3.0 
linter-flake8 2.4.0 
linter-python-pep8 0.2.0 
linter-ui-default 1.7.1 
material-colors 0.1.0 
minimap 4.29.9 
minimap-highlight-selected 4.6.1 
pandoc 0.2.2 
python-autopep8 0.1.3 
python-debugger 0.2.0 
python-indent 1.2.3 
python-tools 0.6.9 
script 3.18.1 
split-diff 1.6.0 
terminal-plus 0.14.5 
```

**Comment by eparimbelli** [comment]
This also happens when trying to reopen a project after just opening atom.
On a mac with big sur 11.04

**Comment by toomas-siim** [comment]
> This also happens when trying to reopen a project after just opening atom.
> On a mac with big sur 11.04

Same for me

**Comment by sugapablo** [comment]
Same here.

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: macOS 11.5
**Thrown From**: [git-merge](https://github.com/AstrickHarren/git-merge) package 0.4.1


### Stack Trace

Uncaught TypeError: Cannot read property 'destroy' of null

```
At /Users/sugapablo/.atom/packages/git-merge/lib/git-merge.js:41

TypeError: Cannot read property 'destroy' of null
    at /packages/git-merge/lib/git-merge.js:41:17
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1186925)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1188366)
    at Project.setPaths (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:413120)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2861897
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:790317)
    at EventEmitter.emit (events.js:223:5)
    at Object.onMessage (electron/js2c/renderer_init.js:115:818)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-typescript 14.3.2 
busy-signal 2.0.1 
escape-utils 0.5.3 
git-merge 0.4.1 
hyperclick 0.1.5 
intentions 2.1.1 
linter 3.4.0 
linter-pylint 2.1.1 
linter-ui-default 3.4.1 
odoo-snippets 0.5.0 
python-autopep8 0.1.3 
script 3.32.2 
split-diff 1.6.1 
```

**Comment by thangtq-pionero** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
dtmkeng, @aoikurokawa, @haolei, @cotoneum, @MrsP3lt, @feewet, @sarmatdev, @sjb933, @refl3ction, @ufoscout, @1500256797, @Perelyn-sama, @mdotstrange, @bigint, @cemozerr, @wemeetagain, @Festoakin77, @wakiyamap, @psbrandt, @j75689
